### ISSUE TITLE
ElfNoteSection is package private

### ISSUE THREAD

**Issue by mikehearn** [fornwall/jelf#12]
Is that intentional? I am trying to detect if an ELF file is a Linux ELF or not and I need to read the `.note.ABI-tag` section for that, but the class isn't available although all the others are. So it looks like an oversight.

**Comment by fornwall** [comment]
Thanks! I've made ElfNoteSection public in version 0.5.0 that is now available in Maven Central.

Does it work for you? Let me know if I can help out!

**Comment by mikehearn** [comment]
Thanks! I'll try it out, but since I filed the bug I've reached the (sad)
conclusion that there's actually no reliable way to detect ELF files
targeting Linux. The ABI tag note *looked* promising, but Rust binaries
don't have them, nor do Go binaries. If there are any commonalities between
such binaries that distinguish them from e.g. Solaris binaries, I can't
find them :(

>
