### ISSUE TITLE
Usage question on ELF specification naming / access

### ISSUE THREAD

**Issue by Col-E** [fornwall/jelf#14]
Hello, my friends and I were looking at adding basic ELF support to [our reverse engineering tool](https://github.com/Col-E/Recaf/pull/423) and found this library. Like #8 says thank you for the useful library. So far we have made some good progress and it looks like we'll be able to mirror the work done on PE display for ELF.

![img](https://media.discordapp.net/attachments/793081672622407681/909129059689197659/unknown.png)

While working on it we came upon some things that we would like to know if there can be some clarification on. 

### The `e_shstrndx` value is private, declared as `private final short sh_string_ndx; // Elf32_Half` in `ElfFile.java`

Making this public is a super quick fix. We can open a PR if you'd like.

### The field names do not always match the [ELF specification](http://www.sco.com/developers/gabi/2000-07-17/ch4.eheader.html). 

It's a bit odd having to tab over to the source in order to find what specification entries correlate to each defined field. In most cases the name differences are pretty minor, and they do all appear in the same order.

Some examples of the differences:

   - `e_phoff` is defined as `ph_offset`
   - `e_phentsize` is defined as `ph_entry_size`

I do think that in general a name like `phentsize` should be a bit more self-documenting such as `ph_entry_size` but since the intent is to parse and mirror an existing specification I'm more inclined to roll with the existing defintions. This is purely a matter of opinion and we were just curious if this sort of reasoning was behind the name differences.

Additionally, while we understand there are some factors to consider against doing so _(Such as backwards compatibility with others using `0.6.0` and older)_, would there be any support for mapping the declarations here to be more specification compliant? Again if you are open to this we would be happy to open a PR for this. 

Thanks

**Comment by fornwall** [comment]
Hi and thanks for your comment!

> Making this public is a super quick fix. We can open a PR if you'd like.

Please do, makes sense!

> This is purely a matter of opinion and we were just curious if this sort of reasoning was behind the name differences.
> Additionally, while we understand there are some factors to consider against doing so (Such as backwards compatibility with others using 0.6.0 and older), would there be any support for mapping the declarations here to be more specification compliant? Again if you are open to this we would be happy to open a PR for this.

- The current naming scheme is not really thought out, and is mostly the result of organic growth over time.
- I don't think backward compatibility is that important at this stage, especially if migration can be done in a straightforward way.
- I'm open to change this, please open a PR!

**Comment by win32kbase** [comment]
Sorry! I meant to do this a while ago and just now got around to doing it. Here's the pull request: https://github.com/fornwall/jelf/pull/15

**Comment by win32kbase** [comment]
> Thanks! This has now been published in version 0.7.0, sorry for the delay!

No problem. Thanks for the merge and the new release! Have a good weekend.
