### ISSUE TITLE
getSymbol from ElfRelocation needs to consider EI_CLASS

### ISSUE THREAD

**Issue by caballa** [fornwall/jelf#18]
This line https://github.com/fornwall/jelf/blob/master/src/main/java/net/fornwall/jelf/ElfRelocation.java#L55 
only works if `EI_CLASS` is `CLASS_32`. 

If `EI_CLASS` is `CLASS_64` then the shift needs to be by 32.

**Comment by fornwall** [comment]
Thanks @caballa ! This has been fixed by https://github.com/fornwall/jelf/commit/7bd84228ccd624d55b8873e735dcc0a82bdf080a.

This is in the [0.8.0 release](https://github.com/fornwall/jelf/releases/tag/v0.8.0).
