### ISSUE TITLE
I cant't get symbol object correctly, in some case

### ISSUE THREAD

**Issue by WXF-wxf1999** [fornwall/jelf#19]
Why does the number of symbols here need to be divided by 2? In my case, I encountered a situation where searching for "poll" symbols failed. The  number of symbol table is 731, but the "poll" is located at position 365, so I just can't get the poll symbol object.  for this line : https://github.com/fornwall/jelf/blob/ec2c1c2540ec86a6956bdb0c552d703674ae7512/src/main/java/net/fornwall/jelf/ElfFile.java#LL403C1-L403C66

**Comment by fornwall** [comment]
Thanks @WXF-wxf1999 for reporting! Should be fixed in https://github.com/fornwall/jelf/commit/c778abda76ad5379e8a7fc06b41c379948f2a1c0, removing the division by 2 (I don't know where that came from).
