### ISSUE TITLE
Incorrect v0.4.3 release

### ISSUE THREAD

**Issue by shamsasari** [fornwall/jelf#6]
The v0.4.3 release is based on 53a9821 which is actually version 0.4.2: https://github.com/fornwall/jelf/blob/53a98213e8025871756a8b4cdf958df39c88d49c/build.gradle#L14

I need the latest version of the code which doesn't read the entire ELF file into memory. For now I'm using Jitpack but it'd be nice to rely on an official release.

Thanks for this work!

**Comment by fornwall** [comment]
Thanks! I've tagged 0.4.4 now, it should show up on Maven central shortly.
